title: University of Doom
email: tim@fanel.li
description: 
baseurl: "/doom.github.io" # the subpath of your site, e.g. /blog/
url: "http://timfanelli.github.io" # the base hostname & protocol for your site
twitter_username: timfanelli
github_username:  doctorbatch

# Build settings
markdown: kramdown
